language: java
sudo: false
jdk:
- oraclejdk8
env:
  matrix:
    - CFENGINE=lucee@4.5
    - CFENGINE=lucee@5
    - CFENGINE=adobe@10
    - CFENGINE=adobe@11
    - CFENGINE=adobe@2016
    - CFENGINE=adobe@9
before_install:
- mkdir /tmp/bin
- export PATH=$PATH:/tmp/bin
install:
- curl --location 'https://www.ortussolutions.com/parent/download/commandbox/type/bin' -o /tmp/box.zip
- unzip /tmp/box.zip -d /tmp/bin
before_script:
- /tmp/bin/box recipe recipeFile=test/ci.boxr CFENGINE=$CFENGINE
- chmod +x test/test.sh
script:
- "./test/test.sh"